repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt -w
        language: system
        types: [go]
        pass_filenames: true

      - id: goimports
        name: goimports
        entry: goimports -w
        language: system
        types: [go]
        pass_filenames: true

      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        files: ^internal/installer/node\.sh$
